eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 20
    leaseExpirationDurationInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka/

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
